all:
	g++ src/main.cpp src/Game.cpp src/Board.cpp src/TextureManger.cpp src/Pieces.cpp  -I/include/Game.hpp  -I/include/Board.hpp -I/include/Pieces.hpp -I/include/TextureManger.hpp  -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf -o out/Chess
	./out/Chess
